# Generated by Django 6.0.2 on 2026-05-02 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='producto',
            new_name='productos_p_estado_7df932_idx',
            old_name='productos_p_estado_b6e196_idx',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='productos_p_categor_15e07f_idx',
            old_name='productos_p_categor_e9c5ca_idx',
        ),
    ]
